export const dummyProjects = [
  {
    id: "p1",
    name: "Mobile App",
    toDos: [
      {
        id: "1",
        title: "Brainstorming",
        image: [],
        description:
          "Brainstorming brings team members' diverse experience into play. ",
        priority: "low",
        comments: 12,
        files: 0,
        users: ["User1", "User3", "User2"],
        status: "not started",
      },
      {
        id: "2",
        title: "Research",
        image: [],
        description:
          "User research helps you to create an optimal product for users.",
        priority: "high",
        comments: 10,
        files: 3,
        users: ["User4", "User5"],
        status: "not started",
      },
      {
        id: "3",
        title: "Wirefreame",
        image: [],
        description:
          "Low fidelity wireframes include the most basic content and visuals.",
        priority: "high",
        comments: 11,
        files: 1,
        users: ["User1", "User5", "User2"],
        status: "not started",
      },
      {
        id: "4",
        title: "Onboarding Illustrations",
        image: ["OnboardingIllustrations"],
        description: "",
        priority: "low",
        comments: 14,
        files: 15,
        users: ["User3", "User2", "User1"],
        status: "started",
      },
      {
        id: "5",
        title: "Moodboard",
        image: ["Moodboard1", "Moodboard2"],
        description: "",
        priority: "low",
        comments: 9,
        files: 10,
        users: ["User2"],
        status: "started",
      },
      {
        id: "6",
        title: "Mobile App Design",
        image: ["MobileAppDesign"],
        description: "",
        priority: "low",
        comments: 12,
        files: 15,
        users: ["User5", "User2"],
        status: "completed",
      },
      {
        id: "7",
        title: "Design System",
        image: [],
        description: "It just needs to adapt the UI from what you did before ",
        priority: "high",
        comments: 12,
        files: 15,
        users: ["User1", "User3", "User2"],
        status: "completed",
      },
    ],
    favColor: "#7AC555",
  },
  {
    id: "p2",
    name: "Website Redesign",
    toDos: [
      {
        id: "1",
        title: "Brainstorming",
        image: [],
        description:
          "Brainstorming brings team members' diverse experience into play. ",
        priority: "low",
        comments: 12,
        files: 0,
        users: ["User1", "User3", "User2"],
        status: "not started",
      },
      {
        id: 2,
        title: "Research",
        image: [],
        description:
          "User research helps you to create an optimal product for users.",
        priority: "high",
        comments: 10,
        files: 3,
        users: ["User4", "User5"],
        status: "not started",
      },
      {
        id: 3,
        title: "Wirefreame",
        image: [],
        description:
          "Low fidelity wireframes include the most basic content and visuals.",
        priority: "high",
        comments: 11,
        files: 1,
        users: ["User1", "User5", "User2"],
        status: "not started",
      },
      {
        id: 4,
        title: "Onboarding Illustrations",
        image: ["OnboardingIllustrations"],
        description: "",
        priority: "low",
        comments: 14,
        files: 15,
        users: ["User3", "User2", "User1"],
        status: "started",
      },
      {
        id: 5,
        title: "Moodboard",
        image: ["Moodboard1", "Moodboard2"],
        description: "",
        priority: "low",
        comments: 9,
        files: 10,
        users: ["User3"],
        status: "started",
      },
      {
        id: 6,
        title: "Mobile App Design",
        image: ["MobileAppDesign"],
        description: "",
        priority: "completed",
        comments: 12,
        files: 15,
        users: ["User5", "User2"],
        status: "completed",
      },
      {
        id: 7,
        title: "Design System",
        image: [],
        description: "It just needs to adapt the UI from what you did before ",
        priority: "completed",
        comments: 12,
        files: 15,
        users: ["User1", "User3", "User2"],
        status: "completed",
      },
    ],
    favColor: "#FFA500",
  },
  {
    id: "p3",
    name: "Design System",
    toDos: [
      {
        id: "1",
        title: "Brainstorming",
        image: [],
        description:
          "Brainstorming brings team members' diverse experience into play. ",
        priority: "low",
        comments: 12,
        files: 0,
        users: ["User1", "User3", "User2"],
        status: "not started",
      },
      {
        id: 2,
        title: "Research",
        image: [],
        description:
          "User research helps you to create an optimal product for users.",
        priority: "high",
        comments: 10,
        files: 3,
        users: ["User4", "User5"],
        status: "not started",
      },
      {
        id: 3,
        title: "Wirefreame",
        image: [],
        description:
          "Low fidelity wireframes include the most basic content and visuals.",
        priority: "high",
        comments: 11,
        files: 1,
        users: ["User1", "User5", "User2"],
        status: "not started",
      },
      {
        id: 4,
        title: "Onboarding Illustrations",
        image: ["OnboardingIllustrations"],
        description: "",
        priority: "low",
        comments: 14,
        files: 15,
        users: ["User3", "User2", "User1"],
        status: "started",
      },
      {
        id: 5,
        title: "Moodboard",
        image: ["Moodboard1", "Moodboard2"],
        description: "",
        priority: "low",
        comments: 9,
        files: 10,
        users: ["User3"],
        status: "started",
      },
      {
        id: 6,
        title: "Mobile App Design",
        image: ["MobileAppDesign"],
        description: "",
        priority: "completed",
        comments: 12,
        files: 15,
        users: ["User5", "User2"],
        status: "completed",
      },
      {
        id: 7,
        title: "Design System",
        image: [],
        description: "It just needs to adapt the UI from what you did before ",
        priority: "completed",
        comments: 12,
        files: 15,
        users: ["User1", "User3", "User2"],
        status: "completed",
      },
    ],
    favColor: "#E4CCFD",
  },
  {
    id: "p4",
    name: "Wireframes",
    toDos: [
      {
        id: "1",
        title: "Brainstorming",
        image: [],
        description:
          "Brainstorming brings team members' diverse experience into play. ",
        priority: "low",
        comments: 12,
        files: 0,
        users: ["User1", "User3", "User2"],
        status: "not started",
      },
      {
        id: 2,
        title: "Research",
        image: [],
        description:
          "User research helps you to create an optimal product for users.",
        priority: "high",
        comments: 10,
        files: 3,
        users: ["User4", "User5"],
        status: "not started",
      },
      {
        id: 3,
        title: "Wirefreame",
        image: [],
        description:
          "Low fidelity wireframes include the most basic content and visuals.",
        priority: "high",
        comments: 11,
        files: 1,
        users: ["User1", "User5", "User2"],
        status: "not started",
      },
      {
        id: 4,
        title: "Onboarding Illustrations",
        image: ["OnboardingIllustrations"],
        description: "",
        priority: "low",
        comments: 14,
        files: 15,
        users: ["User3", "User2", "User1"],
        status: "started",
      },
      {
        id: 5,
        title: "Moodboard",
        image: ["Moodboard1", "Moodboard2"],
        description: "",
        priority: "low",
        comments: 9,
        files: 10,
        users: ["User3"],
        status: "started",
      },
      {
        id: 6,
        title: "Mobile App Design",
        image: ["MobileAppDesign"],
        description: "",
        priority: "completed",
        comments: 12,
        files: 15,
        users: ["User5", "User2"],
        status: "completed",
      },
      {
        id: 7,
        title: "Design System",
        image: [],
        description: "It just needs to adapt the UI from what you did before ",
        priority: "completed",
        comments: 12,
        files: 15,
        users: ["User1", "User3", "User2"],
        status: "completed",
      },
    ],
    favColor: "#76A5EA",
  },
];
